module SeedData
  
  REVIEWS = [
    {rating: 3, reason: "Very Impressed with this simple API at first. Within a week of use however it started freezing up my whole application. It took some configuration to fix, but now I'm moderately satisfied."},
    {rating: 1, reason: "First thing I did after finding this API was to connect it to my website as an update. The software proved a problematic addition, and I would not recommend!"},
    {rating: 5, reason: "Real easy to setup and use right after download. I had not problem with it at all, it is well worth the time it took to configure. I'd recommend this API to anyone!"},
    {rating: 4, reason: "This service easily connects with most any site, and is especially easy to configure with Rails. It adds new dimension to my app, and I'm glad I came acrross it."},
    {rating: 4, reason: "Nice quality backend code, which works great... very happy with this API... need to add 10 more words.."},
    {rating: 5, reason: "Works Great. Implemented on my site effortlessly. Very well designed and built. Definitely worth taking a look at."},
    {rating: 5, reason: "I am impressed with the solid design of this API. I think this is slower than it could be, but it's better than anything I could code myself."},
    {rating: 3, reason: "It needs improvement. I wish I had never installed this API and wasted my time. It renders as a shaky window, which is basically good for nothing."},
    {rating: 5, reason: "I have used a total of 4 APIs to try to achieve this same effect. This one is the best, so I'm happy!"},
    {rating: 4, reason: "Could offer a little more in flexibility of installation, but once you have it set up, it functions as described."},
    {rating: 5, reason: "It was so easy to install. The instructions were simple and so was the process. i was putting off the project for fear. i should have installed it a long ago."},
    {rating: 5, reason: "Easy to install, and works great. Implemented with ease and feels both secure and robustly build. Some solid code lies beneath this service."},
    {rating: 4, reason: "This API did not work for me. I couldn't get it setup, and I tried my hardest. Wouldn't recommend to my friend."},
    {rating: 5, reason: "I showed this to my father, and he was extatic. We've been looking for this typ eof service for a while, and finally here it is! I think it's a hoot."},
    {rating: 3, reason: "This is one of those pieces of software that either works or it doesn't. In my case it most certainly did not, so I'd not recommend."},
    {rating: 4, reason: "This is a basic API that will work on most websites and apps. It's easy to install, and provides a cool service I havn't seen elsewhere."},
    {rating: 5, reason: "I have two similar APIs strung together to extend the functionality of my website. This one is the more powerful of the two, but could still use work on the backened."},
    {rating: 3, reason: "I used this to replace an old service I used before, but is no longer operational. This was an alright replacement. "},
    {rating: 2, reason: "The configuration of my website made it impossible to integrate this API, so I wasn't satisfied. "},
    {rating: 2, reason: "I'm slowly figuring out how to use this program, but the documentation is severely lacking. "},
    {rating: 1, reason: "These days, people seem to have forgotten what a great API is. They'll use just about anything. This one should be put on the bottom of any barell."},
    {rating: 5, reason: "I have used over 5 of these over the years. This one works flawlessy, and can't be beat!"},
    {rating: 5, reason: "I modded this to attach to my iOs app. It's perfect now. I understand it perfectly, and it's not that complicated."},
    {rating: 4, reason: "This is the only API of it's sort worth using. I told some of my developer friends about it, and they all love it too."},
    {rating: 5, reason: "Hello folks its Vince the API Man. I have been a collector and a buff since the dawn of API time, love to do compares. This one is generally ok no major complaints."},
    {rating: 5, reason: "Genuine professional code is the only way to go!  Clean and correct methods.  I like this API.  Thanks!"},
    {rating: 4, reason: "Just downloaded this API. First impressions are good, the buttons are big and easy to locate."},
    {rating: 5, reason: "You can't beat the quality for this API. It's good all-around for every type of implementation."},
    {rating: 3, reason: "Many of my friends use this API, and I wonder why they make such a big deal about it. This isnt backed by the most beautiful code, but it works. "},
    {rating: 5, reason: "I picked this one because of high ratings I saw.  The quality of service does deserve a high rating."},
    {rating: 1, reason: "I downloaded this for an upcoming project. I wasn't impressed. I dont' think I'll use it when it's time to build the project."},
    {rating: 4, reason: "great interface, and works very well. great interface, and works very well.great interface, and works very well."},
    {rating: 4, reason: "As with all APIs, it should be pretty straight forward to setup and keep connected. This is the second project I've used it with. The first one has been up and running on my work network 24/7 for over 2 years with no issues."},
    {rating: 4, reason: "I use everything they roll out. Everything they roll out works for a long time. Slightly more complicated than other similar."},
    {rating: 3, reason: "This is complex application interface that works as described. it seems to work just fine. I would use it again in future projects."},
    {rating: 2, reason: "Remember the old, stiff GUI interfaces from the '90s? This is like that. Don't use it."},
    {rating: 4, reason: "I am a true API freak. this is one of the good ones. Had trouble altering the black lettering on white background though. seems to resiste potential hacker attackers."},
    {rating: 2, reason: "I would have added an extra layer of security to make the API better. beside's that, it's okay, I guess."},
    {rating: 5, reason: "I found this to use as the basis for a hobby project I'm working on. One of the best API's I've worked with thus far! You should use it to."},
    {rating: 4, reason: "Nice API with color coded help assist system. Works exactly as documentation describes."},
    {rating: 4, reason: "Strait forward design and everything is labeled and nicely commented in the documentation, in case you can't figure it out on your own. "},
    {rating: 4, reason: "Used it for a Costa Rica benefit website I build last year. Code isnt as beautiful as a Costa Rican waterfall, but the included CSS does cascade just as well!"},
    {rating: 1, reason: "Maybe I'm doing something wrong, but this API just adds a lot of noise to my app, with no legitimate content parsed from it.."},
    {rating: 5, reason: "This is a great project to get involved with. even if you don't code, download it and get involved."},
    {rating: 5, reason: "Perfect match. Nice backend API with all the fixin's! It's of professional quality, as expected. Works just as advertised and appears to properly format on my app."},
    {rating: 4, reason: "I needed a replacement for an old API that's no longer serviced. Since the old one had almost no extra features, this was a big step up. WOULD RECOMMEND"},
    {rating: 3, reason: "This is a nice little piece of code if you have use for it. Only drawback is that it barely has any documentation at all that I could find."},
    {rating: 4, reason: "I can't complain about this API. It adds as little gear to my website, which is better than having to spin similar code on my own."},
    {rating: 2, reason: "I Prefer other APIS to this one - but to be fair, I found this one after I'd already deployed another one on my production site, so I'm biased.."},
    {rating: 5, reason: "I'm not sure what some people expect when they download this.  As it states in the description, it's meant for one specific function, which it does impecibly.."},
    {rating: 4, reason: "I use this all the time and this little application packs in a lot of features. I'm mostly impressed."},
    {rating: 5, reason: "Works as described. Perfect way to get this service on your app without a lot of work. Great for how much you get for so little config."},
    {rating: 2, reason: "if you are reading reviews about APIs there is something wrong..whats to say them. it's just some lines of code, plopped into a silly file."},
    {rating: 4, reason: "I got this for distribution through my production app. Works like a charm and haven't had an issues."},
    {rating: 5, reason: "Simple and straightforward.  Been looking for a convenient way to do exactly this. Here it is. Thanks for the service!"},
    {rating: 4, reason: "I've been able to use this API with no issues. When I needed to get it connected, it was no big deal. I'm sure I'll use it again on a future project."},
    {rating: 3, reason: "Took me two full days to get it configured right, but it was worth the time! Aside from poor documentation, a perfect API."},
    {rating: 5, reason: "Have used this since the day they launched it. Always high quality and durable code. They're true Pioneers."},
    {rating: 4, reason: "It doesn't feel clunky. It's lite and does't feel like it was built on a cheap budget either."},
    {rating: 5, reason: "I could not find an API to do this for the longest time. Finding this one was a saving grace for me. Thanks!"},
    {rating: 1, reason: "DO NOT USE THIS JUNK... spend a little money and get better quality. I wish I'd read these reviews before I wasted my time."},
    {rating: 1, reason: "What can I say.  Every API needs to work in production, and this one doesn't. Steer clear!"},
    {rating: 3, reason: "The UI on their site sucks, but the API provides a valuable service that I needed!"},
    {rating: 4, reason: "I installed this on two projects I've built over the last year. I like it. My Mom and Dad like it too."},
    {rating: 5, reason: "Really nice search logic on their site, and an outstanding API - I use it primarily for my web app. Recommend you pay for it, not use the free option."},
    {rating: 2, reason: "I really wish that I could yell accolades for this API from a mountaintop.  2 out of 3 success stories does not make this possible for me.  I used it on three projects, and it only works right on two of them."},
    {rating: 2, reason: "This does just what it's supposed to do. But on my app, the UI disagrees with my own logic, and makes it look a bit wonky."},
    {rating: 2, reason: "When I first reviewed this API it was working perfectly for me, now though, it doesn't. I think too much user traffic is messing with their service, and this API is slowing down my whole website as we speak."},
    {rating: 3, reason: "I've had this implemented in my app for years now.  The API still works like the day I installed it. Solid, but no updates to speak up"},
    {rating: 4, reason: "I started using this one because I realized the similar one I had installed before was chargin me a monthly fee I didn't know about. I'm satisfied with this service and it's crystal-clear documentation."},
    {rating: 2, reason: "What's up with this API? This is the WRONG tool for the job I needed it to do. Don't recommend to others with similar needs!"},
    {rating: 3, reason: "I saw this listed on ProductHunt a few months ago, so I thought I'd give it a go. Works pretty well, but doesn't provide any function I really need."},
    {rating: 5, reason: "I installed this on my laptop while I was building an iOs app.  It was to replace one I used before. I use this a lot now, and always rave about it to my friends."},
    {rating: 5, reason: "Bought to use with website. Naturally and it works fantastic . words are not enough to describe the awesomeness of this API!"},
    {rating: 3, reason: "PROS:- Works on any site or app.- Auto menu is very easy to implement (given the documentation is confusing). :) CONS:- Docs are not user friendly.NOTE:Need extra driver for use on windows OSs, or else you get reduced performance"},
    {rating: 5, reason: "This is an excellent piece of software, which is all the more remarkable given its simplicity. I chose the free option, and havn't moved back."},
    {rating: 5, reason: "Works like a charm. Nothing much else to say about it, other than it works exactly like you think it would."},
    {rating: 5, reason: "There's no need to use any other the other brand name APIs that do the same thing. Just use this one and rejoice!"},
    {rating: 3, reason: "This is the same basic structure as the old version, but has increased performance and more features. Definately upgrade to the latest stable release if you haven't already!"},
    {rating:4, reason: "Installed this a couple of times before I got it working just right. Ever since them, I've been a happy user."},
    {rating: 4, reason: "Great replacement for the other one that went down recently. Simple to implement, use, and extend."},
    {rating: 2, reason: "This was a good API at the time I started using it, which was a couple years ago.  Now I realize that I need to try another one, because this one is totally dated."},
    {rating: 5, reason: "I was looking for a decent way to get this effect without a lot of work on my part. This was the answer. Will use again in the future! "},
    {rating: 5, reason: "Like everything else from this company, this API is the height of perfection."},
    {rating: 4, reason: "This API worked out well for my website and, if I were to rebuild tomorrow, I'd use it again."},
    {rating: 5, reason: "The perfect service for API integration. Professional looking and fully configurable. The setup is the easiest I've ever seen."},
    {rating: 1, reason: "The integration sprockets were just as confusing as I feared they'd be, and this API singlehandedly overcomplicated my website to the point of unusability."},
    {rating: 3, reason: "Like most such services; quality is good once you get it working properly. Only time will tell if they'll add more features or not."},
    {rating: 2, reason: "They must have closed-out development on this API. When I installed it, it was fine. Now that browsers are getting updated, it's not working so well anymore."},
    {rating: 2, reason: "The documentation is deceptive. Don't believe it installs as easily or works as smoothly as they claim it does!"},
    {rating: 3, reason: "Seems well built on the hole, but haven't seen it do anything new or revolutionary yet, other than resetting my hole browser all of the sudden for no apparent reason."},
    {rating: 4, reason: "What can I say its API.  The speed is sufficient and the price was right.  What more could you ask for."},
    {rating: 5, reason: "Great quality software to use. I t was a joy to implement. I wish I had another project to install it on right now."},
    {rating: 3, reason: "This API is perfect for my Application, but might not be for yours. Does everything I need."},
    {rating: 4, reason: "I downloaded and installed this on my HP Mini netbook. It seems efficient in terms of processing, and I have no major complaints."},
    {rating: 4, reason: "I've used this service for as long as it's existed.  Does what I need.  Often does things I don't even need it to. "},
    {rating: 4, reason: "This is high-quality code that stands out in the overcrowed API market. I like it, I really like it!"},
    {rating: 4, reason: "Awesome api. though I got it before I learned about other better apis, I don't wanna switch, I'm happy just the way things are."},
    {rating: 3, reason: "The documentation is very short, and I don't think they put much time into it. They put more time into the code, which works aight."},
    {rating: 4, reason: "The frontend service does what it is supposed to do. It doesn't have much diversity in terms of features, but it's solid. "},
    {rating: 4, reason: "Works well, and prevents hackers from intercepting calls in a very unexpected way."},
    {rating: 5, reason: "I not only use this API, I like it so much that I started contributing code to it!"},
    {rating: 5, reason: "Very good, plugs into any project you might be working on. Use it on yours today."},
    {rating: 3, reason: "The only drawback is the speed, it slowed down my site by a few miliseconds per call. That seems like a lot given the minimal complexity of the service itself."},
    {rating: 3, reason: "I've been lookiing for a solid, simple software to perform this function. This does a pretty good job of it, but I want to make my own API that has more features than this one."},
    {rating: 3, reason: "Downloaded this from their website about a year ago, and just started using it in my app today. Docs are detailed and great, code is confusing and clumsy."},
    {rating: 5, reason: "These are by far the best of the three APIs I tried that provide this service. Don't waste your time on the others like i did."},
    {rating: 3, reason: "I guess I was hoping for some kind of magical solution to my API problem. This wasn't it, but it's not a bad piece of software nonetheless."},
    {rating: 2, reason: "I guess my app is getting out of date since this API wouldn't even integrate with my backend. Maybe it's good on Rails, or some other modern site tho."},
    {rating: 3, reason: "There are great APIs, there are terrible APIs, and then there's this one. It's mediocre, the height of alright."},
    {rating: 4, reason: "While it's true that not all APIs are created equal, it's comforting to know some of them (like this one), do exactly what they claim (nothing less, nothing more)"},
    {rating: 4, reason: "We used this API to set up at work, because we needed features it provided. It provided them, and my boss I was happy I told her about it."},
    {rating: 4, reason: "It is a solid bit of code that does a task I need. What more can I say?"},
    {rating: 4, reason: "I have used this service for 4 years, never has any problem, except that it went down for a period of 2 days in 2015."},
    {rating: 3, reason: "It's a clever design and a good idea, but i wouldn't put it in my app unless you really know waht you're doing."},
    {rating: 5, reason: "You can fold up your legs & skip writing code for this function. Just install this API, and eat hot buttered korn."},
    {rating: 5, reason: "Nice little service - very clever design, lite, and it's usefulness knows no bounds."},
    {rating: 2, reason: "I had it working for a few months, but it doesn't anymore. Not sure if the problem's on my end, or on theirs tho."},
    {rating: 5, reason: "Been so far very happy with this API since the day I downloaed it. Installed it on my old laptop first, and it seems to work just about everywhere."},
    {rating: 4, reason: "for the money this is very nice. you may not this so. well, that's your problem."},
    {rating: 2, reason: "The backend integration is not intended to fit all frameworks. Works with some technologies, but not with lower-level languages."},
    {rating: 5, reason: "I have been enjoying APIs of all types for the last 3 years!  Finally found this one and was not disapointed. Check it out if ya haven't already!"},
    {rating: 5, reason: "My wife told me about this service because she likes it, but I like it way more. Use it everyday, sometimes thrice."},
    {rating: 4, reason: "Great code quality. Perfect for my son's first website. He got it installed no problem, and is using it productively."},
    {rating: 5, reason: "I just found this today and was blown away by the imaginitive quality of this API. I have never used a service so cool in all my days."},
    {rating: 3, reason: "MY G/F SEEMS TO BE VERY SATISFIED WITH IT.I GUESS.NO COMPLAINTS ANYWAY."},
    {rating: 4, reason: "I live in the shadow of a hill with almore no wifi that I can steal from the neighbors. This API uses so little bandwidth, it works even in my own position."},
    {rating: 4, reason: "Very good considering its simplicity.  Very sensitive to changes in your backend tho. Use with caution and be sure to have feature tests making sure it still works before you deploy."},
    {rating: 1, reason: "This echoes another API I used once upon a time. It has no real features, but the documentation is phenomenal."},
    {rating: 5, reason: "It certainly does its job, and can be installed by even the least technical of users."},
    {rating: 3, reason: "This actually a little faster after their last update. Still kinda slow, but seems to be getting better all the time."},
    {rating: 4, reason: "Not much to review for this kind of software, but it does it's job perfectly. Didn't break my computer, and delivers the relevant information. "},
    {rating: 4, reason: "Was hard to find documentation on this. I needed some help from StackOverflow, but now it works grrreat."},
    {rating: 4, reason: "WANT TO ADD MORE FUNCTION TO YOUR WEBSITE WITHOUT WORKING TOO HARD THIS IS FOR YOU"},
    {rating: 2, reason: "First of all, I'd like to start by saying that this API does in fact work, however, it does not work well.When connecting to my own website, it was tough to get implemented, and now it's really slow to make calls to the server."},
    {rating: 2, reason: "Worked fine for about 4 months than just stopped working. My mom tried to look at the debug logs and figure out wat the problem was, but no dice."},
    {rating: 4, reason: "A very good APi to know about.  I have a couple sites that use it to great success"},
    {rating: 4, reason: "My goal was acheived quickly and it all works perfectly."},
    {rating: 4, reason: "This is a good software, it works really good, I connected it to my site, and now I like it good."},
    {rating: 5, reason: "Very sturdy and robust in terms of features. You'd have to try in order to make this crash from too many API calls."},
    {rating: 5, reason: "I use this in conjunction with another API, but this one does most of the heavy lifting. Bravo to the dev team!"},
    {rating: 4, reason: "This API works, thats that, no two ways about it, nothing special about this API, nothing wrong about this API "},
    {rating: 5, reason: "Ive used this for a few months now, and power to the people who created it!"},
    {rating: 3, reason: "It took longer then normal to make this run, and calls take longer than normal to complete. Other than that, pretty solid"},
    {rating: 4, reason: "This is a high-quality service that passes data like a champ, no frills no fails."},
    {rating: 1, reason: "This did not hook in to my backend server like I though it would. EPIC FAIL"},
    {rating: 3, reason: "Works fine for windows apps. Doesn't seem to work at all on iOs apps."},
    {rating: 4, reason: "I just discovered that there's an API available for this service, and downloaded it right away. Definately worth the config time."},
    {rating: 4, reason: "Needed this for a project I built during a dev bootcamp. Implemented seamlessly, even though I wasn't a great coder yet."},
    {rating: 5, reason: "Works exactly how it is supposed to. No detectable loss in load speed after installing it."},
    {rating: 3, reason: "Although it doesn't say the makers anywhere in the docs, this did the trick for my purposes."},
    {rating: 4, reason: "I have 2 twin sites that use this API, and it never disapoints."},
    {rating: 4, reason: "I just needed something (this API) to make my website better. THANKS! "},
    {rating: 5, reason: "Well developed, rife with features, and everything works great."},
    {rating: 4, reason: "I wasn't sure what to expect when I installed it, but I'm glad I did. Runs great and improves the functionality I had previous."},
    {rating: 4, reason: "I have just installed this on 2 of by best sites, and it made them even better."},
    {rating: 5, reason: "This is an excellent API, and you should check it out if you havn't already "},
    {rating: 2, reason: "Worked fine for about 2 weeks, then it would no longer get assigned an IP address and was rendered useless."},
    {rating: 5, reason: "This is a very helpful API that saved me a ton of work I would've otherwise had to do on my own."},
    {rating: 5, reason: "Hands-down the best looking API I've seen. Everything has worked as expected and the fast call loads give it serious boner points."},
    {rating: 4, reason: "Excellent API to replace one that had failed on my site last month."},
    {rating: 5, reason: "I love it as you can see the data the API is parsing all the time."},
    {rating: 5, reason: "Have this hooked up to our frontend, and it's cool as a Polar bear on an iceburg."},
    {rating: 3, reason: "This does what it's suppose to, Ive had no trouble with it and would recommend it."},
    {rating: 2, reason: "I compared the speeds with a direct competitors and there was no difference. This one is just sorta annoying to use."},
    {rating: 5, reason: "This API is effective, efficient, and easy to install with pretty much any backend."},
    {rating: 4, reason: "It does not come with its own frontend utility, but you can spin one yourself and harness the power of this API."},
    {rating: 1, reason: "Would be great if it actually works, but it doesn't."},
    {rating: 4, reason: "This comes with a bunch of boilerplate features you can get any number of places. It aggregates them nicely tho, and it's a bad tool to have around."},
    {rating: 3, reason: "I read some other reviews that mentioned this API, so I gave it a try. I've got no use for it, but it seems fairly delightful."},
    {rating: 4, reason: "Installation was very straight forward. Activity is monitored in the log, and you can debug issues with relative ease."},
    {rating: 4, reason: "Very satisfied with API, works great, was loads fast.  What more could one want.  Will definately continued using. "},
    {rating: 3, reason: "Converted our site to use this API when another one went on the fritz. No problem so far, but that was only a couple weeks aggo."},
    {rating: 4, reason: "I use this with my new website and quite like the way it runs."},
    {rating: 4, reason: "As others have said, this API works great and makes the service easy to integrate with anything. "},
    {rating: 5, reason: "I have used this same API for almost 2 years now and it never failed me. I would highly recommend this one, very good."},
    {rating: 4, reason: "This is great service, and sure beats writing the logic on your own."},
    {rating: 5, reason: "All things considered, this is great software. It gets the job done and that's all I care about."},
    {rating: 4, reason: "I've loved this service for years, and their API doesn't disapoint."},
    {rating: 3, reason: "Just what I though it would be when I installed it. Would recomend."},
    {rating: 1, reason: "I needed an upgrade for this API last week, and it broke my whole site. DO NOT USE!!!"},
    {rating: 4, reason: "Works great, attractive UI. They deserve their reputation."},
    {rating: 1, reason: "This is great if it's the only feature on your site. DOES NOT PLAY NICE WITH OTHERS!"},
    {rating: 3, reason: "I have no complaints. doesn't what it says it would, and that's that."},
    {rating: 3, reason: "I like the design, simple and fast. I wish the documentation was better."},
    {rating: 2, reason: "I use this on a site I'm the webmaster for. It's cool, but leaves a lot to be desired."},
    {rating: 5, reason: "This is a must have for ALL developers. Download ASAP!"},
    {rating: 4, reason: "They say it won't work with all apps, but I've yet to find a build it fails with."},
    {rating: 1, reason: "I live in a historic brick building, which means I cannot steal wifi from neighboring buildings. The install file was so big I couldn't download it at the public library. I don't like this API."},
    {rating: 4, reason: "Suits Rails apps fairly well, not sure about other frameworks."},
    {rating: 5, reason: "We have used this API at my company for over a year. It works great for production apps."},
    {rating: 1, reason: "If your able to get this working, then I'm very impressed. I never got it working for a single second."},
    {rating: 3, reason: "Decent API all things considered, but some features work better than others."},
    {rating: 4, reason: "I am quite staisfied with this little piece of software. It has amazing integration with the service, and I'd say installing it on my app was a good decision overall."},
    {rating: 2, reason: "I chose this particular API because I'd tried all the other ones. I guess I'm too picky, cause I wasn't happy with this one either."},
    {rating: 2, reason: "I could not use it - it turns out will not work on a iOs apps, and that's what I needed."},
    {rating: 3, reason: "I gave this item 3 stars, not 5, for the following reasons. It took a long time to set up, and the docs leave a lot to be desired."},
    {rating: 5, reason: "This is a great replacement for the one my company used before. Installs easily and feels very good from a user standpoint."}
]

end
