development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: API-Addicts_development
  pool:     5
  username: API-Addicts
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: API-Addicts_test
  pool:     5
  username: API-Addicts
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: API-Addicts_production
  pool:     5
  username: API-Addicts
  password:
  template: template0
