development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 256dad9efe9021f6c17cfb1e7702730d6c7330d979407844bc04d8c1db916d96cdd5ec6e270b535d0531df5465eee39a9fc45f7e7708e653df1c1cfad2e4d86e

test:
  domain_name: example.com 
  secret_key_base: ed40e9e07e21c9c39d08012386973d1a3d209cd3260db1dd91a13fa510446c878a22124db123aa268c4002deec7adf98b3921f3c590c5fc180467f5476b34dd1

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
